name: Same Old Same Old
description: What has changed since Jacob's last visit to the National Gallery of Art?

defaults:
  -
    scope:
      path: "galleries/*/index.md"
      type: "pages"
    values:
      layout: "gallery"