name: Same Old Same Old
description: What has changed since Jacob's last visit to the National Gallery of Art?

layouts_dir: /_theme/_layouts
includes_dir: /_theme/_includes

collections:
  galleries:
    east: 
      order:
        - index.md
    west: 
      order:
        - index.md

defaults:
  - scope:
      path: "/galleries/east"
    values:
      layout: "default"
      title: "East Gallery"
  - scope:
      path: "/galleries/west"
    values:
      layout: "default"
      title: "West Gallery"